#!/usr/bin/env bash
# Verly (Space Ultroid) - UserBot
# Copyright (C) 2021-2022 TeamUltroid for Ultroid & Space Network for Verly
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.


echo "
            __   __       _
            \ \ / /__ _ _| |_  _
             \ V / -_) '_| | || |
              \_/\___|_| |_|\_, |
                            |__/

      Verly V1.0.0 [Kasperky Cake] by Ultroid & SN

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyUltroid ; fi
